spring.application.name=EcommerceWebAppApi

spring.datasource.url=${DB_URL:jdbc:postgresql://ep-dark-king-ay7d7q9h-pooler.c-5.us-east-2.aws.neon.tech/shopHub}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_p7d6lniZVaTO}

# Driver and Dialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Optional: Helpful for debugging Hibernate/JPA issues
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update